services:
  # 1. O Banco de Dados PostgreSQL
  - type: postgres
    name: api-database
    region: ohio
    plan: free
    databaseName: api_db
    user: api_user

  # 2. A API Flask (Serviço Web)
  - type: web
    name: sua-api-flask
    region: ohio
    runtime: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

    envVars:
      - key: APP_SECRET_KEY
        generateValue: true # O Render vai criar uma chave segura sozinho

      - key: DATABASE_URL
        fromService:
          type: postgres
          name: api-database
          property: connectionString

      - key: PYTHON_VERSION
        value: "3.10.9"

  # 3. O Disco para seus PDFs
  - type: static_site
    name: documentos-pdf
    region: ohio
    plan: free
    # Diretório onde os arquivos estão no seu GitHub
    # IMPORTANTE: crie esta pasta 'documentos_pdf'
    staticPublishPath: ./documentos_pdf