services:
  # 1. O Banco de Dados PostgreSQL
  - type: psql  # <--- CORRIGIDO (deve ser 'psql')
    name: api-database
    region: ohio
    plan: free
    databaseName: api_db
    user: api_user

  # 2. A API Flask
  - type: web
    name: sua-api-flask
    region: ohio
    runtime: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

    envVars:
      - key: APP_SECRET_KEY
        value: "uma-nova-chave-secreta-bem-forte-e-aleatoria"

      - key: DATABASE_URL
        fromService:
          type: psql # <--- CORRIGIDO (deve ser 'psql')
          name: api-database
          property: connectionString

      - key: PYTHON_VERSION
        # Verifique no seu terminal local com 'python --version'
        # e coloque a sua versão ex: 3.10.9, 3.11.4, etc.
        value: "3.10.9"

  # 3. O Disco para seus PDFs
  - type: static
    name: documentos-pdf
    region: ohio
    staticPublishPath: ./documentos_pdf
    # O 'staticRootPath' não é necessário para o Gunicorn
    # Mas precisamos ajustar o 'importar_resultados.py'
(Nota: Eu também ajustei o static service para ser mais simples e adicionei um comentário sobre PYTHON_VERSION para evitar problemas futuros).